### ISSUE TITLE
Yanking all versions of a gem?

### ISSUE THREAD

**Issue by marshally** [rubygems/new-index#1]
New index format looks neat!

Question:

In the case of all versions of a gem being yanked, and someone taking the namespace for a different gem:
http://help.rubygems.org/kb/gemcutter/removing-a-published-rubygem

Will this cause the ETag check to fail and therefore bundler re-downloads the appropriate files?

Marshall

**Comment by indirect** [comment]
Yup, that's exactly why the rtag check exists. That same check also protects against transmission errors and allows us to rewrite the versions list occasionally, consolidating all versions of a single gem down to one line.
