### ISSUE TITLE
Version list format of deps file is not extensible

### ISSUE THREAD

**Issue by sheerun** [rubygems/new-index#3]
Allowing spaces in dependences versions while spaces are used to separate columns in deps file makes this format pretty much not extensible.

How about stripping spaces of all versions like so:

```
1.5.7.rc2 rake:>=0.7.1,activesupport:=1.3.1|ruby:>=1.8.7,rubygems:>1.3.1
```

This allows to add third column (sha?) in future and still use `split(' ')` to separate them.

Also I don't think you should encourage clients to use `split(' ', 2)` because it's not forward-compatible way of parsing files.

**Comment by sheerun** [comment]
Also, it's not the case that splitting second column by ` `and then by`|`is slower than using 3 columns instead, and use`split(' ')`? In first case versions string needs to be traversed 2 times by algorithm.

```
1.5.7.rc2 rake:>=0.7.1,activesupport:=1.3.1 ruby:>=1.8.7,rubygems:>1.3.1
```

**Comment by sheerun** [comment]
OK, I see following:

> The requirements after the | character are currently limited to ruby and rubygems, but could be expanded to include any arbitrary requirement in the future. Code that parses those requirements should ignore unknown keys for future compatibility.

I understand if in future an sha will need to be added there will be something like:

```
1.5.7.rc2 rake:>=0.7.1,activesupport:=1.3.1|ruby:>=1.8.7,rubygems:>1.3.1,sha:673823c4
```

right?

**Comment by indirect** [comment]
Yup, you've got it.
