### ISSUE TITLE
google summer of code project discussion method?

### ISSUE THREAD

**Issue by fotanus** [rubygems/new-index#5]
Hi there again,

I would love to work in this project for google summer of code! But I couldn't find on the [wiki](https://github.com/rubygsoc/rubygsoc/wiki/Ideas-List) any place to share my ideas to the project and receive feedback, like a mailing list. Can someone point me the right direction? Thanks!

[]'s

**Comment by indirect** [comment]
There is a bundler mailing list at the Google Group named "ruby-bundler".

**Comment by fotanus** [comment]
Thanks!

**Comment by fotanus** [comment]
Hi again,

Sorry for bother, but is the [ruby-bundler google group](https://groups.google.com/forum/#!forum/ruby-bundler) this one cited on the wiki?

> We also maintain an active group chat, shared with the Rubygems and Rubygems.org teams, allowing us to discuss and plan as needed. Every contributor is invited to join the group chat, and it can be an extremely useful resource when newer contributors have questions or need clarification.

Or this is other one? 

Thanks!

**Comment by TimMoore** [comment]
@fotanus that's referring to our Slack team. If you'd like to join, send an introduction email to team@bundler.io.

**Comment by fotanus** [comment]
Thanks @TimMoore!
